### ISSUE TITLE
audio file with no recalls: issue 2 - "annotations" window refresh

### ISSUE THREAD

**Issue by pcrutchl** [pennmem/Penn-TotalRecall#26]
I haven't fully investigated this behavior, so I'm not sure exactly when it pops up, but there seems to be an issue of the annotations window not refreshing. The problem doesn't normally exist, but it does appear when dealing with an audio file with no recalls or vocalizations. My guess is that the window doesn't refresh when there are no annotations or pywr markings ([???]) to replace what is currently there.

**Comment by ymasory** [comment]
refresh annotation display on audio file switch, Closed by 4f1ffbecf4c487f212971951da77a96a4f5e1a4a
