### ISSUE TITLE
SSH key creation automated through PTR

### ISSUE THREAD

**Issue by pcrutchl** [pennmem/Penn-TotalRecall#34]
Feature request: SSH key creation initialized/automated through PTR

Rhino username entered into PTR and saved-- dialog box/pref pane?  Note: this could also serve as automatic "enter your name here" for each .ann file

Rhino password would need to be typed twice (scp, ssh) -- directly into Terminal?

Note: rhino defaults to making .ssh folder and authorized_keys file group-writable; this will have to be fixed; both should be chmod 644 I believe.

**Comment by ymasory** [comment]
probably should not be part of the app itself, but a separate video
