### ISSUE TITLE
time system doesn't give credit for long playback periods

### ISSUE THREAD

**Issue by ymasory** [pennmem/Penn-TotalRecall#35]

**Comment by ymasory** [comment]
give credit for playback, Closed by 711fa2cf906ffe127433188c6624bb707b687aec

**Comment by pcrutchl** [comment]
Didn't work. Opened a 1.5-minute file, made two annotations at the beginning, then played through the file, making no further marks. Marked complete at the end. Total came out to be .5 minutes.

**Comment by ymasory** [comment]
write spans on mark complege, Closed by 7cfd0a9a78882884cc5dd60405f77e21771afb4b
